services:
  php:
    container_name: sl_php
    build:
      context: .
      dockerfile: Dockerfile
      args: { PHP_VERSION: "8.2" }
      target: dev
    environment:
#      APP_ENV: dev
      APP_ENV: local
      APP_DEBUG: "1"
      DATABASE_URL: "mysql://root:root@db:3306/slider_lara?serverVersion=5.7.40&charset=utf8mb4"
      REDIS_URL: "redis://redis:6379"
      REDIS_HOST_READ_ONLY: 'redis://redis:6379'
      REDIS_HOST_READ_WRITE: 'redis://redis:6379'
#      ELASTIC_SEARCH_HOST: "http://elasticsearch:9200/"
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
#      elasticsearch:
#        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - slider_lara_net


  nginx:
    container_name: sl_nginx
    image: nginx:1.25-alpine
    ports: ["8001:80"]
    volumes:
#      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
#      - ./.docker/nginx/default.conf:/etc/nginx/templates/default.conf.template:ro
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/app.conf:ro
      - .:/var/www/html:ro
    depends_on: [php]
    networks:
      - slider_lara_net

  db:
    container_name: sl_db
    image: mysql:5.7
    platform: linux/amd64     # run x86_64 image on Apple Silicon
    environment:
      MYSQL_DATABASE: slider_lara
      MYSQL_ROOT_PASSWORD: root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports: ["3307:3306"]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
    networks:
      - slider_lara_net

  redis:
    container_name: sl_redis
    image: redis:7-alpine
    ports: ["6380:6379"]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - slider_lara_net

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#    ports: ["9201:9200"]
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
#      interval: 10s
#      timeout: 5s
#      retries: 10

#  kibana:
#    image: docker.elastic.co/kibana/kibana:6.8.23
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - "5611:5601"
#    depends_on:
#      elasticsearch:
#        condition: service_healthy


networks:
  slider_lara_net:
    driver: bridge
